class GithubRepo {

  int? id;
  String? nodeId;
  String? name;
  String? fullName;
  bool? private;
  String? owner;
  String? htmlUrl;
  String? description;
  bool? fork;
  String? url;
  String? forksUrl;
  String? keysUrl;
  String? collaboratorsUrl;
  String? teamsUrl;
  String? hooksUrl;
  String? issueEventsUrl;
  String? eventsUrl;
  String? assigneesUrl;
  String? branchesUrl;
  String? tagsUrl;
  String? blobsUrl;
  String? gitTagsUrl;
  String? gitRefsUrl;
  String? treesUrl;
  String? statusesUrl;
  String? languagesUrl;
  String? stargazersUrl;
  String? contributorsUrl;
  String? subscribersUrl;
  String? subscriptionUrl;
  String? commitsUrl;
  String? gitCommitsUrl;
  String? commentsUrl;
  String? issueCommentUrl;
  String? contentsUrl;
  String? compareUrl;
  String? mergesUrl;
  String? archiveUrl;
  String? downloadsUrl;
  String? issuesUrl;
  String? pullsUrl;
  String? milestonesUrl;
  String? notificationsUrl;
  String? labelsUrl;
  String? releasesUrl;
  String? deploymentsUrl;
  String? createdAt;
  String? updatedAt;
  String? pushedAt;
  String? gitUrl;
  String? sshUrl;
  String? cloneUrl;
  String? svnUrl;
  String? homepage;
  int? size;
  int? stargazersCount;
  int? watchersCount;
  String? language;
  bool? hasIssues;
  bool? hasProjects;
  bool? hasDownloads;
  bool? hasWiki;
  bool? hasPages;
  bool? hasDiscussions;
  int? forksCount;
  String? mirrorUrl;
  bool? archived;
  bool? disabled;
  int? openIssuesCount;
  bool? allowForking;
  bool? isTemplate;
  bool? webCommitSignoffRequired;
  String? visibility;
  int? forks;
  int? openIssues;
  int? watchers;
  String? defaultBranch;

  GithubRepo.fromJson(Map<String, dynamic> json) {
    id = json['id'] ?? null;
    nodeId = json['node_id'] ?? '';
    name = json['name'] ?? '';
    fullName = json['full_name'] ?? '';
    private = json['private'] ?? false;
    owner = json['owner'] != null ? json['owner']['login'] : null;
    htmlUrl = json['html_url'] ?? '';
    description = json['description'] ?? '';
    fork = json['fork'] ?? false;
    url = json['url'] ?? '';
    forksUrl = json['forks_url'] ?? '';
    keysUrl = json['keys_url'] ?? '';
    collaboratorsUrl = json['collaborators_url'] ?? '';
    teamsUrl = json['teams_url'] ?? '';
    hooksUrl = json['hooks_url'] ?? '';
    issueEventsUrl = json['issue_events_url'] ?? '';
    eventsUrl = json['events_url'] ?? '';
    assigneesUrl = json['assignees_url'] ?? '';
    branchesUrl = json['branches_url'] ?? '';
    tagsUrl = json['tags_url'] ?? '';
    blobsUrl = json['blobs_url'] ?? '';
    gitTagsUrl = json['git_tags_url'] ?? '';
    gitRefsUrl = json['git_refs_url'] ?? '';
    treesUrl = json['trees_url'] ?? '';
    statusesUrl = json['statuses_url'] ?? '';
    languagesUrl = json['languages_url'] ?? '';
    stargazersUrl = json['stargazers_url'] ?? '';
    contributorsUrl = json['contributors_url'] ?? '';
    subscribersUrl = json['subscribers_url'] ?? '';
    subscriptionUrl = json['subscription_url'] ?? '';
    commitsUrl = json['commits_url'] ?? '';
    gitCommitsUrl = json['git_commits_url'] ?? '';
    commentsUrl = json['comments_url'] ?? '';
    issueCommentUrl = json['issue_comment_url'] ?? '';
    contentsUrl = json['contents_url'] ?? '';
    compareUrl = json['compare_url'] ?? '';
    mergesUrl = json['merges_url'] ?? '';
    archiveUrl = json['archive_url'] ?? '';
    downloadsUrl = json['downloads_url'] ?? '';
    issuesUrl = json['issues_url'] ?? '';
    pullsUrl = json['pulls_url'] ?? '';
    milestonesUrl = json['milestones_url'] ?? '';
    notificationsUrl = json['notifications_url'] ?? '';
    labelsUrl = json['labels_url'] ?? '';
    releasesUrl = json['releases_url'] ?? '';
    deploymentsUrl = json['deployments_url'] ?? '';
    createdAt = json['created_at'] ?? '';
    updatedAt = json['updated_at'] ?? '';
    pushedAt = json['pushed_at'] ?? '';
    gitUrl = json['git_url'] ?? '';
    sshUrl = json['ssh_url'] ?? '' ?? '';
    cloneUrl = json['clone_url'] ?? '';
    svnUrl = json['svn_url'] ?? '';
    homepage = json['homepage'] ?? '';
    size = json['size'] ?? 0;
    stargazersCount = json['stargazers_count'] ?? 0;
    watchersCount = json['watchers_count'] ?? 0;
    language = json['language'] ?? '';
    hasIssues = json['has_issues'] ?? false;
    hasProjects = json['has_projects'] ?? false;
    hasDownloads = json['has_downloads'] ?? false;
    hasWiki = json['has_wiki'] ?? false;
    hasPages = json['has_pages'] ?? false;
    hasDiscussions = json['has_discussions'] ?? false;
    forksCount = json['forks_count'] ?? 0;
    mirrorUrl = json['mirror_url'] ?? '';
    archived = json['archived'] ?? false;
    disabled = json['disabled'] ?? false;
    openIssuesCount = json['open_issues_count'] ?? 0;
    allowForking = json['allow_forking'] ?? false;
    isTemplate = json['is_template'] ?? false;
    webCommitSignoffRequired = json['web_commit_signoff_required'] ?? false;
    visibility = json['visibility'] ?? '';
    forks = json['forks'] ?? 0;
    openIssues = json['open_issues'] ?? 0;
    watchers = json['watchers'] ?? 0;
    defaultBranch = json['default_branch'] ?? '';
  }
}
